all:
  inline_object:

    parser_class:    sfInlineObjectParser    # Class used by default for the parser

    # Specify the array of inline object types that can be embedded
    # For example, the below example would process the [photo:name] syntax
    # through the InlineObjectPhoto class.
    
    # types:
    #   photo:     InlineObjectPhoto

    cache:
      enabled:  true
      class:    sfFileCache
      options:
        cache_dir:  <?php echo sfConfig::get('sf_app_cache_dir') ?>/inline_objects

# Configuration for if you have sfContentFilterPlugin installed
  content_filter:
    filters:
      inline_object:
        class:      sfContentFilterInlineObject
        cache:      false
        options:    []