all:
  inline_object:

    # Specify the array of inline object types that can be embedded
    # For example, the below example would process the [photo:name] syntax
    # through the InlineObjectPhoto class.
    
    # types:
    #   photo:     InlineObjectPhoto


    # If inline object relates to a Doctrine model, use the relations key
    # to define a relation to use when retrieving those objects.

    #   product:   InlineObjectProduct
    # 
    # relations:
    #   Product:
    #     MyModel:      Products
    #     AnotherModel: RelatedProducts

    cache:
      enabled:  true
      class:    sfFileCache
      options:
        cache_dir:  SF_APP_CACHE_DIR/inline_objects