all:
  inline_object:

    # Specify the array of inline object types that can be embedded
    # For example, the below example would process the [photo:name] syntax
    # through the InlineObjectPhoto class.
    
    # types:
    #   photo:
    #     class: InlineObjectPhoto


    # If inline object relates to a Doctrine model, use the relations key
    # to define a relation to use when retrieving those objects.

    #   product:
    #     class:  InlineObjectProduct
    #     column: slug                       # The "name" will query on this column
    #     model:  Product                    # The foreign model name.
    #     relations:
    #       MyModel:      Products
    #       AnotherModel: RelatedProducts

    cache:
      enabled:  true
      class:    sfFileCache
      options:
        cache_dir:  SF_APP_CACHE_DIR/inline_objects